Задание 1 Номер 5
Dima12101/HomeWork pull request #10
Opened 2018-02-18 16:59 UTC by Dima12101

2018-02-18 18:44 UTC, yurii-litvinov requested changes
Надо немного поправить

2018-02-18 18:44 UTC, yurii-litvinov commented on Semestr_2/Task_1/Number_5/SortingColumns/Program.cs
> +					if (matrix[0, j] < matrix[0,j - 1])
После запятой нужен пробел

2018-02-18 18:44 UTC, yurii-litvinov commented on Semestr_2/Task_1/Number_5/SortingColumns/Program.cs
> +		static void SortingColumns(int[,] matrix, int countLines, int countColumns)
Матрица сама знает свой размер (у многомерных массивов есть метод GetLength, возвращающий размер по любому измерению), так что передавать countLines и countColumns не нужно.

2018-02-19 19:55 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2018-02-19 19:55 UTC, yurii-litvinov commented on Semestr_2/Task_1/Number_5/SortingColumns/Program.cs
> +						}
Я бы это вынес в отдельный метод, это же Swap для колонки

2018-02-19 20:11 UTC, Dima12101 commented on Semestr_2/Task_1/Number_5/SortingColumns/Program.cs
> +						}
Ага, согласен

2018-02-20 15:53 UTC, merged